package com.example.personal_finance_manager.Models;

public enum TipoCategoria {

    COMIDASYBEBIDAS, SUPERMERCADO, ENTRENAMIENTO, TRANSPORTE, AMISTADESYFAMILIA, CREDITOSYFINANCIACION,
    CUENTASYSERVICIOS, EDUCACION, HOGAR, IMPUESTOS, INDUMENTARIA, INVERSIONES, MASCOTAS, OTROS, SALUDYCUIDADOPERSONAL,
    SHOPPING, SUSCRIPCIONES, VIAJES, PENDIENTEDECATEGORIA, SUELDO
}
